ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    odom0: /zed/zed_node/odom
    odom0_config: [true,  true,  true,
                  true,  true,  true,
                  false, false, false
                  false, false, false,
                  false, false, false]

    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    odom1: /mavros/local_position/odom
    odom1_config: [true,  true,  true,
                  true,  true,  true,
                  false, false, false
                  false, false, false,
                  false, false, false]
    
    odom0_relative: false
    odom1_differential: false
    odom1_queue_size: 10

    imu0: /mavros/imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    odom0_relative: false
    odom1_differential: false
    odom1_queue_size: 10
