ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    # since zed imu data is internally fused we dont fuse it here.

    odom0: /zed/zed_node/odom
    odom0_config: [true,  true,  true,
                  false,  false,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    odom0_differential: false
    odom0_relative: true
    odom0_queue_size: 10
    odom0_pose_use_child_frame: true

    imu0: /mavros/imu/data_raw
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    # gravitational acceleration is present in raw data so we remove it here.
    imu0_remove_gravitational_acceleration: true 


    pose0: /mavros/local_position/pose
    pose0_config: [true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 10
    