
services:
  mavros_container:
    image: dev:mavros2
    privileged: true
    ipc: host
    pid: host
    volumes:
      - /dev:/dev
      - ./mavros_entrypoint.sh:/mavros_entrypoint.sh
    entrypoint: ["/bin/bash", "-c", "/mavros_entrypoint.sh"]

  zed_container:
    image: xtrana:ros2
    runtime: nvidia
    privileged: true
    ipc: host
    pid: host
    depends_on:
      - mavros_container
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "-c", "/entrypoint.sh"]
