ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    print_diagnostics: true
    debug: false
    publish_tf: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    
    # since zed imu data is internally fused we dont fuse it here.

    odom0: /zed/zed_node/odom
    odom0_config: [true,  true,  true,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    odom0_differential: false
    odom0_relative: true
    odom0_queue_size: 5
    odom0_pose_use_child_frame: false

    